name: roman-data-workshop-env

dependencies:
  - jupyter
  - notebook >= 6.0
  - matplotlib >= 3.2
  - ipympl
  - numpy >= 2.0
  - packaging
  - pip
  - python == 3.11
  - pyyaml
  - pip:
      - asdf_standard
      - asdf >= 4.1.0
      - asdf-astropy == 0.8.0
      - astropy >= 7.0
      - gwcs >= 0.25.2
      - stpipe >=0.10.0,<0.11.0
      - romancal >= 0.20.0
      - stpsf >= 2.0.0
